### ISSUE TITLE
Talk Proposal: Making your life easy with Vim

### ISSUE THREAD

**Issue by vaibhavk** [osdc/meetups#11]
* Into to Vim & Neovim
* **Exit Vim**
* Get things done without plugins (mostly)
* Some Useful plugins

**Comment by ryzokuken** [comment]
Let's have this next week. @darkHarry can we timeslot this? We'll probably need an LT.

**Comment by code-monk08** [comment]
Finalized Meetup Details:

Date - 2019, January 31
Venue - G3
Time - 5-7 P.M.
