### ISSUE TITLE
Next Meetup topic.

### ISSUE THREAD

**Issue by code-monk08** [osdc/meetups#17]
can we have a meetup on efficient *drafting of proposals* for events like SOC?
hope the meetup could answer some of the questions like,

- how to make an optimized and acheivable plan in terms of project contributions?
- what do the organizations expect from an applicant?
- what factors lead to "building name" in the community?
- how much effective a portfolio site or something similar can be?

**Comment by nightwarrior-xxx** [comment]
Where we can discuss about
 - Projects
 -  Blog
 -  How can we motivate students to attend meetups and contribute
 -  GSOC
@ryzokuken  @darkHarry  @Sudeepam97  @V1shvesh
