### ISSUE TITLE
Add meetup dates and Agendas.

### ISSUE THREAD

**Issue by sidntrivedi012** [osdc/meetups#2]
Proposal of addition of dates and agendas of various meetups going to be organised by OSDC. Will help everyone get prepared for it beforehand.

**Comment by darkHarry** [comment]
We can only have a tentative timeline like <doing this> in <this month>.

**Comment by sidntrivedi012** [comment]
Yes,I had got this idea by seeing the list of meetups here- https://github.com/facebook-developer-circle-delhi/Meetup-Resources

**Comment by sidntrivedi012** [comment]
@darkHarry  Adding `doing this` for every month will indeed, be great.

**Comment by sidntrivedi012** [comment]
Should I make a PR with a table in README with columns as- `Month`,`Date` , `Meetup` , ` Details` ?

**Comment by sidntrivedi012** [comment]
@darkHarry PTAL.

**Comment by sidntrivedi012** [comment]
@V1shvesh @darkHarry @Sudeepam97 I have made a PR for the same.Please take a look at it.

**Comment by darkHarry** [comment]
The table is certainly better.
Closing this Issue now. : )
