### ISSUE TITLE
i3 Talk Proposal

### ISSUE THREAD

**Issue by BK1603** [osdc/meetups#32]
## Title : 
Getting started with i3wm and ricing

## Abstract
The talk will contain an introduction to tiling window managers and i3 specifically, discussing the benefits of using a (tiling) window manager instead of using the generally bloated desktop environments, followed by a session on what is ricing and how to rice i3wm, where I will install and rice i3 on my laptop answering any questions the listeners may have.

Outline:
 - What are window managers
 - What is special about tiling window managers
 - What is i3
 - Why should I use i3
 - How to install i3
 - How to operate i3
 - What is ricing
 - Me installing i3 and ricing it

## Expected Duration
 25-30 mins

## Track
- Beginner

## Talk Type
- [X] Free Talk
- [ ] Talk + Hands On 

## Pre-requisites
None

## Resources
https://i3wm.org/docs/
https://www.youtube.com/playlist?list=PL5ze0DjYv5DbCv9vNEzFmP6sU7ZmkGzcf

**Comment by sidntrivedi012** [comment]
@BK1603 Will you be able to deliver the talk in the meetup this week?

**Comment by BK1603** [comment]
@sidntrivedi012 is it today?

**Comment by sidntrivedi012** [comment]
Nope, not today but maybe Thursday?

**Comment by BK1603** [comment]
@sidntrivedi012 sure! Thursday seems fine :smile:

**Comment by vaibhavk** [comment]
Please increase the duration to 45 minutes
I doubt if covering so many topics can be done in 30 minutes especially the last one 😄

**Comment by sidntrivedi012** [comment]
@BK1603 can you please add the link of the slides?
