### ISSUE TITLE
[Talk-Proposal] How to begin with Kernel Development

### ISSUE THREAD

**Issue by VARoDeK** [osdc/meetups#47]
## Expected Duration
 1-1.5 hrs

## Track
Beginner/ Intermediate

## Talk Type
- [x] Free Talk
- [x] Talk + Hands On 

## Pre-requisites
Linux, Git

**Comment by sidntrivedi012** [comment]
@VARoDeK scheduled your talk for this coming Tuesday's meetup. Thanks :)

**Comment by VARoDeK** [comment]
More than happy to speak. :D

**Comment by sidntrivedi012** [comment]
@VARoDeK Even we are excited. Expecting a great session ahead.

**Comment by VARoDeK** [comment]
I will try my best not let anyone down. Will be my first workshop as a speaker in 62.
