### ISSUE TITLE
[Talk-Proposal] Deno + my project (YouTube API client library)

### ISSUE THREAD

**Issue by akshgpt7** [osdc/meetups#49]
## Abstract
I want to share about a project I'm currently working on. It's a YouTube Data API client library for Deno, written in TypeScript. 
The project is still underway, and I just want to share my progress and learnings. 

## Expected Duration
 15-20 minutes

## Track
Beginner
## Talk Type
- [x] Free Talk
- [ ] Talk + Hands On 

## Slides
https://docs.google.com/presentation/d/1IVRUDFXGrtYqHXHUdoawDPYPU0Xc9r_bVtImdRrFJxk/edit?usp=sharing

**Comment by sidntrivedi012** [comment]
@akshgpt7 Will you do it in the meetup next week ?

**Comment by akshgpt7** [comment]
Sure!

**Comment by akshgpt7** [comment]
Just one question, Do I need to prepare slides for sharing a project?

**Comment by sidntrivedi012** [comment]
If you need to discuss any theoretical concepts, you can make a doc having the api workflow / flow chart etc in order to help others understand better. But that too if needed, totally on your discretion. Its not mandatory.

**Comment by sidntrivedi012** [comment]
Scheduled for the meetup on Tuesday 28/04/2020. Thanks for the proposal 💯 🎉
