### ISSUE TITLE
Introduction to Neovim

### ISSUE THREAD

**Issue by BK1603** [osdc/meetups#50]
## Abstract
An introductory talk to neovim. What is neovim? Why should I use it? How to configure it?
Followed by a brief explanation of my neovim config.

## Expected Duration
30 mins

## Track
Beginner

## Talk Type
- [X] Free Talk
- [ ] Talk + Hands On 

## Pre-requisites
A working linux system for anyone who wants to get a hands on.

## Resources
`:h tutor`
https://learnvimscriptthehardway.stevelosh.com/

## Slides
https://docs.google.com/presentation/d/1ZmYVWbnPvThR3xCok0DdhNxmHViYM7P075hjdcva3vE/edit?usp=sharing

**Comment by BK1603** [comment]
Will upload the resources soon! 
:)

**Comment by sidntrivedi012** [comment]
Scheduled for the meetup this Friday. Thanks for the proposal 💯 🎉

**Comment by sidntrivedi012** [comment]
Thanks for the talk @BK1603 👍
