### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by Arnav-Khare** [osdc/meetups#55]
### New feature

A Bot for OSDC discord server

**Comment by Arnav-Khare** [comment]
Here is the repo for discord bot : https://github.com/Arnav-Khare/OSDC-Discord-Bot#discord-bot

**Comment by daemon1024** [comment]
@Arnav-Khare Great 🚀🥳 Can you share a gif showing the working of the bot?

**Comment by Arnav-Khare** [comment]
@daemon1024 
![Demo](https://user-images.githubusercontent.com/55575931/96713312-04318400-13be-11eb-855e-492058eda512if)

**Comment by Arnav-Khare** [comment]
![Demo](https://user-images.githubusercontent.com/55575931/96736556-5bdde880-13da-11eb-9d1e-e80b24f487ff.gif)

**Comment by daemon1024** [comment]
Closed with https://github.com/osdc/bots/pull/45

Thanks for the great work @Arnav-Khare . Would you like to conduct a session in one of the next meetup regarding how it works and how to get contributing to it?

**Comment by Arnav-Khare** [comment]
Definitely....🙂🙂

**Comment by daemon1024** [comment]
@Arnav-Khare Great👍🎉 Open up another issue with "Submit a Talk" template, with some formalised details of what would you like to speak about ☺️
