### ISSUE TITLE
Weekly Community Meetup #2

### ISSUE THREAD

**Issue by daemon1024** [osdc/meetups#60]
Hello Folks! 👋🏽 

We resumed our weekly meetups last Friday, to streamline things more, we will be opening this issue thread each week from here on.

**What's the weekly meetup about?**
We'll be going around talking about what we learned, currently working on or just something cool we discovered over the course of the week (don't worry even if it's not tech related). If anyone wants to talk about something in a bit of detail, we welcome you to present it to others after we go round the table once. 

**What is thread about?**
This thread will act as a way to gather important announcements/events across the community which includes announcements about upcoming foss events, major feats by community members etc. Also, If you are interested to talk about something in detail please check out the next section.

**Call For Proposals**
Please comment down in the thread about the topic and expected length of the talk. We expect the talks/demo to be [lightning talks](https://en.wikipedia.org/wiki/Lightning_talk) i.e. around 5-10 mins of length. If you want to talk about it much more detail, you can open up a new issue using [this template](https://github.com/osdc/meetups/issues/new?assignees=&labels=&template=talk-proposal.md&title=%5BTalk-Proposal%5D). Really appreciate any kind of knowledge sharing session in the meetups.

**Date, Time and Venue**
TBA

**Comment by Amitpatil215** [comment]
#### [Proposal for lightning talk] 
### [Null Safety](https://dart.dev/null-safety) eliminating [The Billion Dollar Mistake ](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions)

One of the most common pitfalls in many programming languages, is that accessing a member of a `null` reference will result in a null reference exception. In Java this would be the equivalent of a `NullPointerException` and similar type of exceptions could be expected in other languages like cpp, dart, kotlin, go, Javascript, etc.

Some sub-topics would be:
- Why null in the first place?
- How to minimise these errors?
- How `Null Safety` in dart improved development experience and Performance of [Flutter ](https://flutter.dev/?gclsrc=ds&gclsrc=ds)Apps?

**Expected Length** : 15 mins

cc: @daemon1024
