### ISSUE TITLE
Weekly Community Meetup #`3

### ISSUE THREAD

**Issue by Amitpatil215** [osdc/meetups#61]
Hello Folks! 👋🏽

We resumed our weekly meetups, to streamline things more, we will be opening this issue thread every week (Last week thread [here](https://github.com/osdc/meetups/issues/60))

**What's the weekly meetup about?**
We'll be going around talking about what we learned, currently working on or just something cool we discovered over the course of the week (don't worry even if it's not tech related). If anyone wants to talk about something in a bit of detail, we welcome you to present it to others after we go round the table once.

**What is thread about?**
This thread will act as a way to gather important announcements/events across the community which includes announcements about upcoming foss events, major feats by community members etc. Also, If you are interested to talk about something in detail please check out the next section.

**Call For Proposals**
Please comment down in the thread about the topic and expected length of the talk. We expect the talks/demo to be [lightning talks](https://en.wikipedia.org/wiki/Lightning_talk) i.e. around 5-10 mins of length. If you want to talk about it much more detail, you can open up a new issue using this [template](#). Really appreciate any kind of knowledge sharing session in the meetups.

**Do you have any question for us?**
We got you covered fill this anonymous [form](https://forms.gle/E47ehKEMPBFKKBrW6), We will handpick questions and discuss them in this meetup.

**Date, Time and Venue**
Saturday 18 Sept, 2021 
10 PM

<details>
<summary>Template for lightning talk</summary>

```
**[Proposal for lightning talk]**

### Title

<!--- Short Description -->

**Expected Length** : 00 mins

```

</details>

**Comment by phyBrackets** [comment]
[Proposal for lightning talk]

**Introduction to One of the most disruptive technology "Blockchain"** 

_Blockchain is poised to change IT in much the same way open-source software did a quarter of a century ago. And in the same way that Linux took more than a decade to become a cornerstone in modern application development, blockchain will take years to become a lower cost, more efficient way to share information between open and private networks .As a peer-to-peer network, combined with a distributed time-stamping server, blockchain databases can be managed autonomously to exchange information between disparate parties. There’s no need for an administrator. In effect, the blockchain users are the administrator.

Some sub-topics would be: 

- Talk about Decentralization 
-  What actually is Blockchain? 
- An Overview of Bitcoin and Ethereum.
- Some Open Source Project related to Blockchain.

Expected Length : 25 mins
cc- @Amitpatil215

**Comment by Amitpatil215** [comment]
Thank you for the wonderful session!

Meeting Notes [here](https://github.com/osdc/meetups/blob/master/meetup_2021-22/3_intro_to_blockchain_by_shivam_rajput_18_Sept_21.md)

Closing this `CFP` thread as meetup notes added by PR #63 and merged.
