### ISSUE TITLE
Segregate tables for Formal and Informal Meetups

### ISSUE THREAD

**Issue by darkHarry** [osdc/meetups#8]
The issue is totally explained in the title. Shall we have two tables for normal meetups where we just talk and discuss and one for where we teach and give a talk?

**Comment by ryzokuken** [comment]
Don't know, as long as we're meeting, it's okay to call it a meetup, right?

**Comment by ryzokuken** [comment]
And how is it better than adding an extra column to say if it was formal or not? Maybe that'll be easier in the longer run? Fill it with emojis like ✅ and ❌ .

**Comment by darkHarry** [comment]
That sounds better and less work.

**Comment by sidntrivedi012** [comment]
@ryzokuken @darkHarry I had added the ** as a marker. Totally forgot to see this issue.

Should I add another row and use the emojis for signifying the formal and informal meetups?

**Comment by darkHarry** [comment]
Works for me.
