### ISSUE TITLE
Update the git-github meetup files

### ISSUE THREAD

**Issue by darkHarry** [osdc/meetups#9]
@vaibhavk Can you commit the git-github meetup files ?

**Comment by darkHarry** [comment]
If anyone remembers the link to the Github repo of the git electron app we used in our git-github meetup then please do the following : 

- [ ] Add a txt file with the link to the Github repo of the app
- [ ] Add the presentation created by @vaibhavk
- [ ] Put the above in a folder named `git-github-meetup-1`

**Comment by vaibhavk** [comment]
Github repo : https://github.com/jlord/git-it-electron
Presentations : https://vaibhavk.github.io/presentations
Presentation Source : https://github.com/vaibhavk/presentations

**Comment by code-monk08** [comment]
anything more in this issue? else, It can be closed.
